### ISSUE TITLE
Incomplete protocol implementation

### ISSUE THREAD

**Issue by ralfbeuschel** [RobTillaart/M62429#4]
I have tested the code today with a WONDROM VC01-M62429[615] module and an Arduino Nano board.

The WONOM board is based on the It is based on the M62429 chip (https://store.sure-electronics.com/product/AA-AA11117). I tested with a digital scope against the rotary encoder board deliverd with the module.

After a two hour debug session I finally got the code running. It turned out that the protocol implementation in the _setVolume function is incomplete. According to the datasheet two "H" bits are required at the end of transmission (D9 and D10). The current software only sends a single high bit instead of two. The chip is also very strict about the data low phase after every bit and the latch timing.

Here's the corrected code. 
I did not check if the setup and hold timing is satisfied on faster processors than the Nano board. Potentially more delay functions are needed.

void M62429::_setVolume(uint8_t channel, uint8_t attn)
{
  uint16_t databits = 0xFE00;           // latch bits
  databits |= (attn & 0x007C);
  databits |= ((attn & 0x03) << 7);
  // channel == 2 -> both 0x00 is default
  if (channel == 0) databits |= 0x03;   // 11
  if (channel == 1) databits |= 0x02;   // 01

  for (uint16_t mask = 1; mask < 0x0200; mask <<= 1)
  {
    digitalWrite(_data, databits & mask);
    digitalWrite(_clock, HIGH);
    // Note that if clock pulses are long enough the data pulses are automatically too.
    if (M62429_CLOCK_DELAY > 0) delayMicroseconds(M62429_CLOCK_DELAY);

    digitalWrite(_data, LOW);
    digitalWrite(_clock, LOW);
    if (M62429_CLOCK_DELAY > 0) delayMicroseconds(M62429_CLOCK_DELAY);
  }
  // Send D9 high bit
  digitalWrite(_data, HIGH);
  digitalWrite(_clock, HIGH);
  if (M62429_CLOCK_DELAY > 0) delayMicroseconds(M62429_CLOCK_DELAY);

  // note that the data signal must be set to low for every bit.
  digitalWrite(_data, LOW); 
  digitalWrite(_clock, LOW);
  if (M62429_CLOCK_DELAY > 0) delayMicroseconds(M62429_CLOCK_DELAY);

  // Send D10 high bit (Latch signal)
  digitalWrite(_data, HIGH);
  digitalWrite(_clock, HIGH);
  if (M62429_CLOCK_DELAY > 0) delayMicroseconds(M62429_CLOCK_DELAY);

  // latch signal requires clock low before data
  // make _data dummy write to keep timing constant
  digitalWrite(_data, HIGH);
  digitalWrite(_clock, LOW);
  if (M62429_CLOCK_DELAY > 0) delayMicroseconds(M62429_CLOCK_DELAY);
  
  digitalWrite(_data, LOW);
  if (M62429_CLOCK_DELAY > 0) delayMicroseconds(M62429_CLOCK_DELAY);
}

**Comment by RobTillaart** [comment]
Thanks for testing and fixing the issue.
 I will dive into this asap but that might take a few days as i need to reread the datasheet details again.

**Comment by RobTillaart** [comment]
Found a timeslot today. Checked my hardware but no IC's so I need to order them for testing.

**Comment by RobTillaart** [comment]
looked at your code and indeed a bug in the latch bits.

As I prepared the latch bits in **databits** the code below shifts out the D9 bit also in the loop.
This makes the code a bit shorter.

As I have no HW around can you please verify this version?

```cpp
// attn = 0, 3..87
void M62429::_setVolume(uint8_t channel, uint8_t attn)
{
  uint16_t databits = 0xFE00;               //  D10 - D9  latch bits
  databits |= ((attn & 0x03) << 7);         //  D8  - D7  volume bits
  databits |= (attn & 0x007C);              //  D6  - D2  volume bits
  // channel == 2 -> both 0x00 is default
  if (channel == 0) databits |= 0x03;       //  D0  - D1  channel bits
  if (channel == 1) databits |= 0x02;       //  D0  - D1  channel bits

  // write D0 - D9
  for (uint16_t mask = 1; mask < 0x0400; mask <<= 1)
  {
    digitalWrite(_data, databits & mask);
    digitalWrite(_clock, HIGH);
    // Note that if clock pulses are long enough the data pulses are automatically too.
    if (M62429_CLOCK_DELAY > 0) delayMicroseconds(M62429_CLOCK_DELAY);

    digitalWrite(_data, LOW);
    digitalWrite(_clock, LOW);
    if (M62429_CLOCK_DELAY > 0) delayMicroseconds(M62429_CLOCK_DELAY);
  }

  // Send D10 HIGH bit == 2nd latch bit
  digitalWrite(_data, HIGH);
  digitalWrite(_clock, HIGH);
  if (M62429_CLOCK_DELAY > 0) delayMicroseconds(M62429_CLOCK_DELAY);

  // last latch bit requires clock low before data
  // make _data dummy write to keep timing constant
  digitalWrite(_data, HIGH);
  digitalWrite(_clock, LOW);
  if (M62429_CLOCK_DELAY > 0) delayMicroseconds(M62429_CLOCK_DELAY);

  digitalWrite(_data, LOW);
  if (M62429_CLOCK_DELAY > 0) delayMicroseconds(M62429_CLOCK_DELAY);
}

```

**Comment by RobTillaart** [comment]
mmm, just noticed different edge when data is clocked. does not affect the code. 

raises the question why one should make D9 HIGH and LOW before reading?

![image](https://user-images.githubusercontent.com/462844/147742573-ea75928f-2432-4f97-9238-a32c037dd74b.png)

**Comment by RobTillaart** [comment]
Created PR - https://github.com/RobTillaart/M62429/pull/5
Branch - https://github.com/RobTillaart/M62429/tree/Fix_4

**Comment by ralfbeuschel** [comment]
I'll try to find a time slot next week for testing with the hardware.

Am 30.12.2021 um 11:32 schrieb Rob Tillaart:

**Comment by RobTillaart** [comment]
> Found a timeslot today. Checked my hardware but no IC's so I need to order them for testing.

Ordered 2x FM62429  (next:  find a big chunk of time)

**Comment by RobTillaart** [comment]
@ralfbeuschel 

> I'll try to find a time slot next week for testing with the hardware. 

Any progress?

**Comment by ralfbeuschel** [comment]
Sorry no progress in the past week.... too busy with everything. I'm not 
in a big hurry with this project.

Ralf

Am 09.01.2022 um 12:32 schrieb Rob Tillaart:

**Comment by RobTillaart** [comment]
@ralfbeuschel 
Got time and hardware to build a test setup, tested and verified and it is working as intended (UNO).
Added an interactive example which made testing a bit easier.

Will merge the PR coming weekend unless I encounter a showstopper.
